#cloud-config

package_upgrade: true

runcmd:
  - /bin/bash <(curl -fsSL https://raw.githubusercontent.com/softvisio/scripts/main/setup-host.sh)

  - /bin/bash <(curl -fsSL https://raw.githubusercontent.com/softvisio/scripts/main/setup-timesync.sh)

  - 'hostname $(curl -s "http://metadata.google.internal/computeMetadata/v1/instance/name" -H "Metadata-Flavor: Google").$(curl -s "http://metadata.google.internal/computeMetadata/v1/project/project-id" -H "Metadata-Flavor: Google")'

  - hostname > /etc/hostname

  - apt-get install -y docker-ce

  # - docker swarm init

  # - docker network create --driver overlay --attachable main
